name: multimodal_framework
description: A structured FSM-based mental health screening application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Networking
  http: ^1.2.0

  # Utilities
  uuid: ^4.3.3
  shared_preferences: ^2.2.2

  # Camera
  camera: ^0.10.5+5

  # Permissions
  permission_handler: ^11.3.1

  # Audio recording
  record: ^5.0.4

  # File paths
  path_provider: ^2.1.2

  # Icons
  cupertino_icons: ^1.0.6

  # Visualization
  fl_chart: ^0.68.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true